baseURL = "https://jamia97.github.io/"
languageCode = "en-us"
title = "JamiA97"
copyright = "No copyright."

rssLimit = 20
staticDir = "static"
canonifyURLs = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[author]
	name = "JamiA97"
	email = "example@mail.com"

[params]
  description = "This is my first site"

[markup.goldmark.renderer]
    unsafe = "true"
